title: earlook99
tagline: Unreal Engine, C++
description: Studying Computer Engineering with a focus on Unreal Engine and
  aspiring to become a game client developer. Interested in indie game
  development and computer graphics, exploring creative ideas and technical
  challenges in the field.
url: https://earlook99.github.io
baseurl: ""
lang: ko-KR
timezone: Asia/Seoul
cdn: https://chirpy-img.netlify.app
avatar: /commons/avatar.jpg
social_preview_image: null
github:
  username: earlook99
social:
  name: Hohyeon Lee
  email: earlook99@gmail.com
  fediverse_handle: null
  links:
    - https://github.com/earlook99
webmaster_verifications:
  ? google
  ? bing
  ? alexa
  ? yandex
  ? baidu
  ? facebook
analytics:
  google:
    ? id
  goatcounter:
    ? id
  umami:
    ? id
    ? domain
  matomo:
    ? id
    ? domain
  cloudflare:
    ? id
  fathom:
    ? id
pageviews:
  ? provider
theme_mode: null
toc: true
paginate: 10
comments:
  provider: null
  disqus:
    ? shortname
  utterances:
    ? repo
    ? issue_term
  giscus:
    ? repo_id
    ? strict
    ? reactions_enabled
    ? mapping
    ? lang
    ? repo
    ? category_id
    ? category
    ? input_position
assets:
  self_host:
    ? enabled
    ? env
pwa:
  enabled: true
  cache:
    enabled: true
    deny_paths: null
theme: jekyll-theme-chirpy
kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
collections:
  tabs:
    output: true
    sort_by: order
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/
  - scope:
      path: admin
    values:
      sitemap: false
sass:
  style: compressed
compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs:
      - development
exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - purgecss.js
  - "*.config.js"
  - package*.json
jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
